services:
  app:
    image: ${APP_IMAGE_NAME:-idempotent-api}:${APP_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${APP_CONTAINER_NAME:-idem-demo-app}
    ports:
      - "${APP_PORT:-8080}:8080"
