spring.application.name=idempotent-api

server.port=8080

spring.cache.type=caffeine
spring.cache.cache-names=idempotencyKeys
spring.cache.caffeine.spec=expireAfterWrite=30s,maximumSize=10000

spring.quartz.job-store-type=memory
spring.quartz.scheduler-name=IdempotentScheduler

logging.level.org.springframework.web=INFO
